sudo: false

branches:
  except:
    - /^v[-.0-9]+$/

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install: true

script: mvn -Plibrary verify

cache:
  directories:
    - $HOME/.m2
    - bower_components
    - node
    - node_modules
