sudo: required
dist: trusty

branches:
  except:
    - /^v[-.0-9]+$/

language: java

jdk:
  - oraclejdk8

install: true

before_script:
  - npm run yarn-clean

script: mvn -Plibrary verify

cache:
  directories:
    - $HOME/.m2
    - node

after_success:
  - git clone https://github.com/perfectsense/travis-maven-deploy.git && travis-maven-deploy/deploy.sh
