env:
  nvm:
    - DISABLE_NOTIFIER=true

sudo: required
dist: trusty

branches:
  except:
    - /^v[-.0-9]+$/

language: node_js
node_js:
  - "6.1"

before_script:
  - npm install -g gulp

script: gulp

cache:
  directories:
    - node

after_success:
  - git clone https://github.com/perfectsense/travis-maven-deploy.git && travis-maven-deploy/deploy.sh
