
network: network.yml

layers:

  - name: development
    image: brightspot-base [development] hvm [11]
    instanceType: m3.large
    rolePolicies:
      - beam-server-readonly
      - create-describe-amis
      - s3-full-access

    securityRules:
      - development
      - operations

    provisioners:
    - type: knife-solo
      cookbookPath: ../chef
      recipe: brightspot-base::development

    placements:
      - subnetType: development
        sizePerSubnet: 1
        hostnames:
          - "dev.brightspot-base.psdops.com."
          - "*.dev.brightspot-base.psdops.com."
          - "jenkins.brightspot-base.psdops.com."
